# Generated by Django 4.0.3 on 2022-03-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=100, verbose_name='main_user'),
        ),
    ]
