# Generated by Django 4.0.3 on 2022-03-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_webp', models.ImageField(blank=True, null=None, upload_to='', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
